### ISSUE TITLE
Golden Cookie counter

### ISSUE THREAD

**Issue by Mtarnuhal** [Mtarnuhal/FrozenCookies#11]
Golden Cookie Counter takes twice as long and the minimum is guaranteed golden cookie.

**Comment by geojak** [comment]
I cant follow you on this. do you mean cycle in the botton left takes twice as long to load? comparded to old versions? I am sorry, could you please elaborate it a bit more for me, i am too dumb^^

**Comment by Mtarnuhal** [comment]
Already found out the issue. Due to the framerate update my frame rate went from 30 to 15 and so my golden cookie timer left bottom went from 1:55min average to 3:50 average.

**Comment by geojak** [comment]
sorry for that! need to check the setting again now that the other change is merged
