### ISSUE TITLE
Efficiency Table out of sync when having a limit on Farms, Towers and Cursors

### ISSUE THREAD

**Issue by Mtarnuhal** [Mtarnuhal/FrozenCookies#13]
I've noticed that when I have Wizard Tower Cap on that the efficiency table is slowly losing percentages.
[https://i.imgur.com/2cqhrej.png](https://i.imgur.com/2cqhrej.png)

I think this has to do that the building/upgrade is still on the FrozenCookies.caches list.

**Comment by geojak** [comment]
Might be because those buildings(farm,wizard, cursors) are the most efficient to buy (as we capped the number lower than what auto buy would want) but they are blacklisted. since in the calculations farm cursors and wizard towers are still used, the remaining ones not blacklisted have only low efficiency compared to farms,cursors,Wizards

Have to check to code what actually is going on.

**Comment by Mtarnuhal** [comment]
Well, they aren't actually blacklisted. They are removed from the array in the "function recommendationList" after the efficiency score has been added.

**Comment by adavidw** [comment]
The easiest approach is just to probably recalculate the efficiency scores/percentages relative to the rest of the array after those items with limits have been removed. However, I'm noticing that the entire recommendations engine runs really slowly, especially at the beginning of an ascension, so I'm wary of adding any new calculations to it. So, we'll probably have actually do it the right way and account for those earlier in the process. Maybe pick up some performance gains to boot.

**Comment by Mtarnuhal** [comment]
I agree that it runs slow at the beginning of an ascension. this is mostly due to that the further you are in the game the faster it can buy the next thing and recalculates the list at that point.
if we can exclude them from being picked up in the list before it gets calculated then that would fix. I don't think it will give us a performance boost.
