### ISSUE TITLE
Sugar Lump Harvesting

### ISSUE THREAD

**Issue by MetaNite64** [Mtarnuhal/FrozenCookies#18]
I turned on SL harvesting for a little bit while a bifurcated lump was MATURE, but not ripe. Frozen Cookies immediately botched the harvest.

**Comment by Seven-709** [comment]
I have running Frozen Cookie now for quite some time and I can confirm that there seems something wrong with the SL harvesting function as well as SL + Rigidel. I suspect, that Frozen Cookie is try to harvest SL too fast, meaning FC is already harvesting while for the game the SL is still mature and not ripe, resulting in a 50% chance of fail. Maybe a short artifical delay or a check if an SL is "really" ripe before triggering the actual harvest would be helpful. Just measuring times might be not accurate enough.
