### ISSUE TITLE
Can't decrease the FPS

### ISSUE THREAD

**Issue by 64BTX** [Mtarnuhal/FrozenCookies#20]
Clicking the FPS button only increases the value. I might be doing something wrong, but I can't figure out how to decrease it.

**Comment by Mtarnuhal** [comment]
FPS Button is a Cycle button with set values. Keep Clicking it and will go to lower FPS values.
`var fps_amounts = ['24', '30', '48', '60', '72', '88', '100', '120', '144', '200', '240', '300', '5', '10', '15'];`
