### ISSUE TITLE
How to debug?

### ISSUE THREAD

**Issue by chrisheib** [Mtarnuhal/FrozenCookies#38]
Hey, I enjoy this addon much!  
I want to tinker around with the code a bit, maybe i can add some nice things to it, but i don't know how to test a local, changed version with the game. How do you guys debug this? Can this maybe be added to a contributors.md or something?

**Comment by Mtarnuhal** [comment]
What I do is fork it then make a dev branch.
Change the URL in the bookmark, userscript, and frozen_cookie file. using https://raw.githack.com/ to make the right raw git call.
Open the game load the changed script to test. 

But maybe some of the contributors have a better way.
