### ISSUE TITLE
Achievement notification popups bugged

### ISSUE THREAD

**Issue by shrx** [Mtarnuhal/FrozenCookies#52]
Initially opened an issue on reddit: https://old.reddit.com/r/CookieClicker/comments/jjvdwt/heavy_flow_achievement_bugged/

Later it turned out that frozen cookies incorrectly reports the achievement as unlocked.

Probably something related to the `fcWin` code?  https://github.com/Mtarnuhal/FrozenCookies/blob/master/fc_main.js#L2003

It would be nice to have an option to disable these popups since they don't seem to work properly.

**Comment by Mtarnuhal** [comment]
We'll look into this.
Which browser are you using?
Could you provide us a copy of your game save so we can test our solutions?

**Comment by nobuhiiro** [comment]
Hi, I'm having a similar issue, every time and action occurs, I have the same achievements being spawned. Even If I enable or disable an option in the options menu of FC.
I'm ussing Mozilla Firefox Developer Edition (83.0b6 (64-bit))
Here is an example : https://imgur.com/a/CV1kufL
This is my save: [PirateGnomeBakery.txt](https://github.com/Mtarnuhal/FrozenCookies/files/5462332/PirateGnomeBakery.txt)

**Comment by shrx** [comment]
Thanks for the fix!
