### ISSUE TITLE
 Autobulk does not work after legacy.

### ISSUE THREAD

**Issue by kotenok2000** [Mtarnuhal/FrozenCookies#54]

**Comment by adavidw** [comment]
I'm not seeing anything going wrong here. I just ran through a few tests again, and it seems like it's working fine. Is it reproducible? Can you give any more idea of what you're seeing or what your settings are?

**Comment by kotenok2000** [comment]
I am seeing that autobuy buys buildings one by one.
i will attach exported save.
[ProfessorPancakeBakery.txt](https://github.com/Mtarnuhal/FrozenCookies/files/5462403/ProfessorPancakeBakery.txt)

**Comment by kotenok2000** [comment]
I am using frozen cookies 1.9.0 from https://mtarnuhal.github.io/FrozenCookies/fc_userscript_loader.user.js   on mozilla firefox

**Comment by kotenok2000** [comment]
Update: I have reset progress to the beginning of the run.
New save:
[ProfessorPancakeBakery(1).txt](https://github.com/Mtarnuhal/FrozenCookies/files/5462451/ProfessorPancakeBakery.1.txt)
I enabled autobuy and auto bulkbuy x10

**Comment by adavidw** [comment]
I can't reproduce with either save file.

**Comment by Mtarnuhal** [comment]
The autoBulk functions doesn't switch to the accorded set in the setting.
It only switch to the bulk buy if it can actually buy in that mode.
As far as I know, this is intended for autoAscension. While you can change it back to buy x1 halfway in the ascension.

https://i.imgur.com/FPPqPcA.mp4

**Comment by Mtarnuhal** [comment]
Can you make a screenshot of your settings?

**Comment by kotenok2000** [comment]
Autoascension disabled
