### ISSUE TITLE
Missing prefs

### ISSUE THREAD

**Issue by mithrandi** [Mtarnuhal/FrozenCookies#60]
Auto-godzamok and maybe others have disappeared; related to the sections change I guess?

**Comment by Mtarnuhal** [comment]
As far as I can see all preferences are there.
![image](https://user-images.githubusercontent.com/2243505/97849528-f69bc880-1cf2-11eb-949a-e30815d52624.png)
Can you send a screenshot of your preference section?

**Comment by mithrandi** [comment]
Ah doh, this is a graphical bug in Chrome dev channel that also affects the main Options; so not FC's fault.
