### ISSUE TITLE
'Time till completion' seems to be incorrect

### ISSUE THREAD

**Issue by nebocco** [Mtarnuhal/FrozenCookies#67]
Hi, I have a question about the calculation of compilation time.
since the current CPS is about 5 million / sec, to reach 1.161 billion (cost of Next Purchase) it would take less than 5 minutes. However, 'Time till compilation' is over 8 hours. in addition, 'Estimated Actual time completion' doesn't decrease over time.
Is the script moving correctly? 
![スクリーンショット 2020-11-23 103907](https://user-images.githubusercontent.com/73807432/99923668-1f573100-2d7a-11eb-8f78-2c65935db553.png)

**Comment by adavidw** [comment]
How many cookies were in the bank when this screenshot was taken? I assume the longer time is for building up the golden cookie bank?

**Comment by nebocco** [comment]
Oh, I didn't know that the Autobuyer doesn't purchase anything if cookies in the bank would be lower than the golden cookie bank. I had only 40 million cookies then, so I'm sure you're right. Thanks for the simple explanation!
