### ISSUE TITLE
User script doesn't work in Greasemonkey

### ISSUE THREAD

**Issue by piels** [Mtarnuhal/FrozenCookies#76]
I've just recently switched to Firefox, and started playing with Greasemonkey instead of Tampermonkey.  The current fc_userscript_loader.user.js doesn't work in Greasemonkey, i.e. Game.LoadMod is never called.  

It looks like the result of some security-related Firefox and Greasemonkey changes that happened back in 2017, which would mean it hasn't worked in 3 or 4 years.   Can anyone confirm this?

**Comment by Mtarnuhal** [comment]
Might be just greasemonkey related. It works on tampermonkey for firefox.
![image](https://user-images.githubusercontent.com/2243505/114217391-611ef780-9968-11eb-9dc7-01378e02e339.png)
