### ISSUE TITLE
Not loading on steam.

### ISSUE THREAD

**Issue by JourneyOver** [Mtarnuhal/FrozenCookies#83]
Have tried loading it through creating a

info.txt
```
{
	"Name": "Frozen Cookies",
	"ID": "frozen cookies",
	"Author": "Chevron42 - Mtarnuhal",
	"Description": "An automated Cookie Clicker tool.",
	"ModVersion": 2.031,
	"GameVersion": 2.031,
	"Date": "25/07/2021",
	"Dependencies": [],
	"Disabled": 1,
	"AllowSteamAchievs": 1
}
```

main.js
```
Game.LoadMod("https://mtarnuhal.github.io/FrozenCookies/frozen_cookies.js");
```

Not sure if something needs to be changed or what exactly..

The only error that comes up in the console (can be seen by going into the start.js file and switching `let DEV=0;` to `let DEV=1;`) is this:
`frozen_cookies.js:82 GET file://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js net::ERR_FILE_NOT_FOUND`

**Comment by Mtarnuhal** [comment]
I haven't checked it for the steam game. I'll take a look next week.

**Comment by JourneyOver** [comment]
Great! Hope you can get it figured out and working, as frozen cookies is a really good mod and I miss it.

**Comment by JourneyOver** [comment]
Since Icehawk came back to the cookie clicker world and made a update to make FC work on the steam version, I am going to go ahead and close this issue.
