### ISSUE TITLE
Expose Building Efficiency list

### ISSUE THREAD

**Issue by Frustrated-Programmer** [Mtarnuhal/FrozenCookies#88]
I'm making a mod that sorts the building list, https://github.com/Frustrated-Programmer/BuildingSorter

I'd like to include a sorter for YOUR mod, that sorts all buildings based on the efficiency of purchasing it. But not sure how to access your efficiency per building. So, I'm sure you already check the efficiency of each building and find the highest efficiency for AutoBuy to function. 

I'm asking you to **expose** the efficiency for EACH building, it doesn't even need to be sorted as my sorter would sort the building list anyways.

**Comment by Mtarnuhal** [comment]
I hope this is what you are looking for.
`FrozenCookies.caches.recommendationList`
or 
`recommendationList()`
This will give you back an array of the efficiency table.

**Comment by Frustrated-Programmer** [comment]
That is exactly what I'm looking for! Thank you so much.
